# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push tests
# run-name: ${{ github.actor }} push tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 2.7.18
#          - python: 3.7.14
          - python: 3.12.8
          - python: 3.13.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: "${{ matrix.python }}"
      - name: Setup Env
        run: |
          pip install --upgrade pip
          pip install -e .
          pyenv -v
      - name: test
        run: |
          python -m unittest discover
  coverage:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.10.11
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: "${{ matrix.python }}"
      - name: Setup Env
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install -U coveralls coverage
      - name: test coverage
        run: |
          coverage run -m unittest discover
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
